
export enum Role {
    ADMINISTRADOR = 'ADMINISTRADOR',
    COORDENACAO = 'COORDENACAO',
    DIRETORENSINO = 'DIRETORENSINO',
    COORDENADORCURSO = 'COORDENADORCURSO',
    PROFESSOR = 'PROFESSOR',
}